/**
 * Type declarations for static image imports (`import logo from "…/logo.png"`).
 *
 * Next.js normally supplies these through `next-env.d.ts`, but that file is
 * generated by `next build`/`next dev` and is gitignored — so a clean checkout
 * running `tsc --noEmit` on its own, as CI does before the build step, has no
 * declaration for `.png` and fails with TS2307.
 *
 * Referencing the types directly makes the typecheck self-sufficient.
 */

/// <reference types="next/image-types/global" />
